language: generic 
sudo: required
services: 
  - docker 

before_install:
  - docker build -t ltlouie/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true ltlouie/docker-react npm run test